version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Tokyo
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  commit-message:
    prefix: chore
    include: scope
